#!/usr/bin/env ruby

require 'the_jekyll_editor'

# ===================
# CONFIGURATION
# ===================

# iblog="/Users/ruvido/Dropbox/web/matrimoniofrancescano.it"
# idump="#{iblog}/__writing"

iblog="/Users/ruvido/Desktop/5p2p"
idump="/Users/ruvido/Dropbox/Writing drafts/5p2p"

myblog=Blogdata.new( idump, iblog )

# change default path for blog images
myblog.blog_images="#{iblog}/img/posts"
# myblog.blog_previews="#{iblog}/preview_posts"

[ myblog.dump_drafts, myblog.dump_previews ].each do |cdir|


  Dir["#{cdir}/{[!_]**/*,*}.md"].each do |ii|

    # puts cdir

    puts '--------------------------------'


    draft=Draft.new(ii,myblog)
    status = draft.status
    puts draft.basename
      if draft.image
        puts draft.image
      end
    puts status

    case status
    when "publish"
      draft.to_posts
      # puts "file published!"
    when "preview"
      draft.missing
      draft.to_previews
      # puts "file sent to previews, want the address?"
    when "draft"
      # puts "keep working on that!"
    end    

  end
  # puts '--------------------------------'
end

# sleep 1
myblog.push
